"""
dashboard.py
------------
Streamlit dashboard visualizing OEE, SPC control limits, bottleneck detection,
and before/after Kaizen improvement results.

Run: streamlit run dashboard.py
(Requires data/*.csv already generated by simulate.py -> analyze.py -> improve.py)
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

st.set_page_config(page_title="Line Sight — DMAIC Dashboard", layout="wide")

st.title("🏭 Line Sight — DMAIC-Based Bottleneck Detection Dashboard")
st.caption("Simulated 4-stage bottling line: Filling → Capping → Labeling → Packaging")

try:
    oee_df = pd.read_csv("data/oee_by_station_shift.csv", parse_dates=["shift_date"])
    raw_df = pd.read_csv("data/production_log.csv", parse_dates=["timestamp"])
except FileNotFoundError:
    st.error("Data not found. Run `python simulate.py` then `python analyze.py` first.")
    st.stop()

# ---- Top KPI row ----
avg_oee_by_station = oee_df.groupby("station")["oee"].mean().sort_values()
bottleneck = avg_oee_by_station.index[0]

col1, col2, col3, col4 = st.columns(4)
col1.metric("Overall Line OEE", f"{oee_df['oee'].mean()*100:.1f}%")
col2.metric("Bottleneck Station", bottleneck)
col3.metric("Total Shifts Logged", f"{oee_df['shift_date'].nunique()}")
col4.metric("Total Units Produced", f"{oee_df['units_produced'].sum():,}")

st.divider()

# ---- OEE by station ----
st.subheader("OEE by Station")
c1, c2 = st.columns([2, 1])
with c1:
    fig, ax = plt.subplots(figsize=(8, 4))
    avg_oee_by_station.sort_values().plot(
        kind="barh",
        ax=ax,
        color=["red" if s == bottleneck else "steelblue" for s in avg_oee_by_station.sort_values().index]
    )
    ax.set_xlabel("Average OEE")
    ax.axvline(0.85, color="green", linestyle="--", label="World-class OEE (85%)")
    ax.legend()
    st.pyplot(fig)
with c2:
    st.dataframe(avg_oee_by_station.round(3).rename("Avg OEE"))
    st.info(f"**{bottleneck}** has the lowest OEE — it constrains total line throughput per Theory of Constraints.")

st.divider()

# ---- SPC chart for bottleneck ----
st.subheader(f"SPC Control Chart — {bottleneck}")
station_data = oee_df[oee_df["station"] == bottleneck].sort_values("shift_date").reset_index(drop=True)
x = station_data["throughput_per_hr"]
mean, std = x.mean(), x.std()
ucl, lcl = mean + 3 * std, mean - 3 * std

fig2, ax2 = plt.subplots(figsize=(10, 4))
ax2.plot(station_data.index, x, marker="o", markersize=4, label="Throughput/hr")
ax2.axhline(mean, color="green", label="Center line")
ax2.axhline(ucl, color="red", linestyle="--", label="UCL (+3σ)")
ax2.axhline(lcl, color="red", linestyle="--", label="LCL (-3σ)")
out = station_data[(x > ucl) | (x < lcl)]
if len(out):
    ax2.scatter(out.index, out["throughput_per_hr"], color="red", s=70, zorder=5, label="Out of control")
ax2.set_xlabel("Shift #")
ax2.set_ylabel("Units/hr")
ax2.legend()
st.pyplot(fig2)

st.divider()

# ---- Pareto chart on downtime causes ----
st.subheader(f"Pareto Root Cause Analysis — {bottleneck} Downtime")
downtime_df = raw_df[(raw_df["station"] == bottleneck) & (raw_df["event_type"] == "downtime")]
cause_totals = downtime_df.groupby("cause")["duration_sec"].sum().sort_values(ascending=False)
cum_pct = (cause_totals / cause_totals.sum() * 100).cumsum()

fig3, ax3 = plt.subplots(figsize=(9, 4))
ax3.bar(cause_totals.index, cause_totals.values / 60, color="steelblue")
ax3.set_ylabel("Downtime (min)")
ax3.set_xticks(range(len(cause_totals)))
ax3.set_xticklabels(cause_totals.index, rotation=20, ha="right")
ax4 = ax3.twinx()
ax4.plot(range(len(cause_totals)), cum_pct.values, color="darkorange", marker="o")
ax4.axhline(80, color="red", linestyle="--")
ax4.set_ylabel("Cumulative %")
st.pyplot(fig3)

st.divider()

# ---- Before/after improvement, if available ----
st.subheader("Improvement Impact (DMAIC: Improve + Control)")
try:
    summary = pd.read_csv("data/improvement_summary.csv")
    row = summary.iloc[0]
    c1, c2, c3 = st.columns(3)
    c1.metric("Throughput", f"{row['throughput_after']:.1f} u/hr", f"{row['throughput_gain_pct']:+.1f}%")
    c2.metric("Downtime", f"{row['downtime_after_sec']:,} sec", f"-{row['downtime_reduction_pct']:.1f}%")
    c3.metric("OEE", f"{row['oee_after']*100:.1f}%", f"{(row['oee_after']-row['oee_before'])*100:+.1f} pts")
    st.success(f"Kaizen intervention on **{row['bottleneck_station']}** improved throughput by "
               f"{row['throughput_gain_pct']:.1f}% and cut downtime by {row['downtime_reduction_pct']:.1f}%.")
except FileNotFoundError:
    st.warning("Run `python improve.py` to generate before/after improvement results.")
